/*
 *  -----driver.c-----
 *  Designed to be called by the Python driver as part of the flow
 *  Pipeline steps:
 *    - create shared memory
 *    - grab shared memory in Python driver
 *    - Start Python input handlers
 *    - Initialize GST, Raylib
 *    - Run the playback driver
 *
 * */
#include "../include/assets.h"
#include <Python.h>
#include <sys/mman.h>

// error handling
#include <errno.h>
#include <stdio.h>
#include <string.h>

void *create_shared_memory() {
  /*
   *  Creates a shared memory space of a VideoState object.
   *  Returns a void pointer of the shared memory so Python can
   *  do with it what it wants
   *
   *  Returns
   *  -------
   *  shared_memory : void*
   *    The shared memory generated by the function
   * */
  VideoState *state = create_video_state();

  assert(state != NULL);

  int protection = PROT_READ | PROT_WRITE;
  int visibility = MAP_SHARED | MAP_ANONYMOUS;

  void *shmem = mmap(state, sizeof(VideoState), protection, visibility, -1, 0);

  if (shmem == NULL) {
    printf("shared memory could not be generated\n");
    perror("Error message");

    return NULL;
  }

  return shmem;
}

int video_start(int argc, char *argv[], void *shmem, PyObject *event_emitter) {
  /*
   *  Configures all necessary plugins (?) in order to start the playback
   * driver. Also carries some important arguments needed for input management.
   *
   *  Parameters
   *  ----------
   *  argc : int
   *    Basic argc from C, the number of arguments given to the program
   *  argv : char*
   *    All arguments given to the program
   *  shmem : void*
   *    The shared memory created in `create_shared_memory`
   *    Really a pointer to the `VideoState` struct
   *  event_emitter : PyObject*
   *    Passed in from the Python driver, a `threading.Event` object
   *    used to set() the signal for commands
   * */

  /*
   *  ---VALIDATE PARAMETERS---
   * */
  if (argc <= 1) {
    printf("Please provide arguments when calling this program.\n");
    return -1;
  }
  assert(event_emitter != NULL);
  assert(shmem != NULL);

  char *media_path = argv[1];
  // cast shared memory address to its true value
  VideoState *state = (VideoState *)shmem;

  /*
   *  ---RAYLIB INITIALIZING---
   * */
  RaylibVideo *stream = load_video(media_path);
  if (stream == NULL) {
    printf("Could not generate video stream\n");
    return -1;
  }

  // configs here
  SetConfigFlags(FLAG_WINDOW_RESIZABLE);
  InitWindow(stream->width, stream->height, "YouTube Looper");
  SetTargetFPS(60);
  SetExitKey(KEY_NULL);

  /*
   *  ---GST INITIALIZING---
   * */
  gst_init(NULL, NULL);
  init_empty_texture(stream);
  create_gstreamer_pipeline(stream);

  /*
   *  ---MAIN DRIVER---
   * */
  playback_driver(stream, state, event_emitter);

  /*
   *  ---EXITING---
   * */
  destroy_stream(&stream);
  printf("Done exiting\n");

  return 1;
}
